version: "3.8"

services:
  spring:
    container_name: spring
    image: insoo0111/ending-credits
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - es
    networks:
      - api-net

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=endingcredits
      - POSTGRES_PASSWORD=endingcredits
    ports:
      - "5432:5432"
    networks:
      - api-net

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=ending-credits
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=endingcredits
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - api-net

networks:
  api-net:
    driver: bridge
