version: "3.8"

services:
  spring:
    container_name: spring
    image: insoo0111/ending-credits
    ports:
      - "8080:8080"
    volumes:
      - /var/log/:/logs/
    depends_on:
      - db
      - es
    networks:
      - api-net

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=endingcredits
      - POSTGRES_PASSWORD=endingcredits
    ports:
      - "5432:5432"
    networks:
      - api-net

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - node.name=single-node
      - cluster.name=ending-credits
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=endingcredits
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - api-net

networks:
  api-net:
    driver: bridge
