version: "3.8"

services:
  spring:
    container_name: spring
    image: insoo0111/ending-credits
    ports:
      - "8080:8080"
    volumes:
      - /var/log/:/logs/
    depends_on:
      es:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - api-net

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=endingcredits
      - POSTGRES_PASSWORD=endingcredits
      - POSTGRES_DB=endingcredits
    ports:
      - "5432:5432"
    networks:
      - api-net
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U endingcredits" ]
        interval: 10s
        retries: 5
        timeout: 5s

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - node.name=single-node
      - cluster.name=ending-credits
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - api-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  api-net:
    driver: bridge
